"""
Workflow Health Monitor.

Monitors workflow health, detects issues, predicts bottlenecks,
and triggers appropriate actions to prevent SLA breaches.
"""

from __future__ import annotations

import asyncio
from dataclasses import dataclass
from datetime import datetime, timedelta
from enum import Enum, auto
from typing import Any, Callable, Dict, List, Optional, Set
from collections import defaultdict

from pydantic import BaseModel, Field


class HealthStatus(Enum):
    """Health status levels."""
    HEALTHY = auto()
    WARNING = auto()
    CRITICAL = auto()
    UNKNOWN = auto()


class AlertSeverity(Enum):
    """Alert severity levels."""
    INFO = auto()
    WARNING = auto()
    ERROR = auto()
    CRITICAL = auto()


class HealthCheck(BaseModel):
    """Result of a health check."""
    check_name: str
    status: HealthStatus
    message: str
    details: Dict[str, Any] = Field(default_factory=dict)
    timestamp: datetime = Field(default_factory=datetime.utcnow)


class HealthAlert(BaseModel):
    """An alert generated by health monitoring."""
    id: str
    severity: AlertSeverity
    title: str
    description: str
    
    # Context
    workflow_id: Optional[str] = None
    execution_id: Optional[str] = None
    step_id: Optional[str] = None
    
    # Timing
    created_at: datetime = Field(default_factory=datetime.utcnow)
    expires_at: Optional[datetime] = None
    
    # Status
    acknowledged: bool = False
    resolved: bool = False
    resolved_at: Optional[datetime] = None
    
    # Recommendations
    recommended_actions: List[str] = Field(default_factory=list)


class SLADefinition(BaseModel):
    """SLA definition for monitoring."""
    name: str
    target_completion_hours: float
    warning_threshold_percent: float = 75.0  # Warn at 75% of time
    escalation_threshold_percent: float = 90.0  # Escalate at 90%
    applicable_urgency: List[str] = Field(default_factory=lambda: ["critical", "high", "normal", "low"])


class BottleneckPrediction(BaseModel):
    """Prediction of a potential bottleneck."""
    resource: str  # What's bottlenecked (person, step, system)
    severity: str  # low, medium, high
    predicted_impact: str
    confidence: float
    timeframe: str
    recommendations: List[str] = Field(default_factory=list)


class WorkflowMetrics(BaseModel):
    """Metrics for a workflow type."""
    workflow_id: str
    
    # Volume
    total_executions: int = 0
    active_executions: int = 0
    completed_today: int = 0
    
    # Performance
    avg_duration_seconds: float = 0.0
    p95_duration_seconds: float = 0.0
    success_rate: float = 1.0
    
    # Health
    current_health: HealthStatus = HealthStatus.HEALTHY
    active_alerts: int = 0
    
    # Trends
    duration_trend: str = "stable"  # improving, stable, degrading
    success_trend: str = "stable"


class WorkflowMonitor:
    """
    Monitors workflow health and predicts issues.
    
    Features:
    - Real-time health monitoring
    - SLA tracking
    - Bottleneck prediction
    - Alert generation
    - Trend analysis
    """
    
    def __init__(
        self,
        check_interval_seconds: float = 30.0,
        alert_callback: Optional[Callable[[HealthAlert], None]] = None
    ):
        self._check_interval = check_interval_seconds
        self._alert_callback = alert_callback
        self._running = False
        self._monitor_task: Optional[asyncio.Task] = None
        
        # Tracking data
        self._workflow_metrics: Dict[str, WorkflowMetrics] = {}
        self._active_alerts: Dict[str, HealthAlert] = {}
        self._sla_definitions: Dict[str, SLADefinition] = {}
        
        # Execution tracking
        self._execution_starts: Dict[str, datetime] = {}
        self._execution_durations: Dict[str, List[float]] = defaultdict(list)
        
        # Resource tracking
        self._resource_utilization: Dict[str, float] = {}  # resource_id -> utilization %
        self._resource_queues: Dict[str, int] = defaultdict(int)  # Pending items per resource
        
        # Health check registry
        self._health_checks: List[Callable[[], HealthCheck]] = []
    
    def register_sla(self, sla: SLADefinition) -> None:
        """Register an SLA definition."""
        self._sla_definitions[sla.name] = sla
    
    def register_health_check(self, check: Callable[[], HealthCheck]) -> None:
        """Register a custom health check."""
        self._health_checks.append(check)
    
    def track_execution_start(
        self,
        workflow_id: str,
        execution_id: str
    ) -> None:
        """Track the start of an execution."""
        self._execution_starts[execution_id] = datetime.utcnow()
        
        if workflow_id not in self._workflow_metrics:
            self._workflow_metrics[workflow_id] = WorkflowMetrics(workflow_id=workflow_id)
        
        self._workflow_metrics[workflow_id].total_executions += 1
        self._workflow_metrics[workflow_id].active_executions += 1
    
    def track_execution_complete(
        self,
        workflow_id: str,
        execution_id: str,
        success: bool
    ) -> None:
        """Track the completion of an execution."""
        start_time = self._execution_starts.pop(execution_id, None)
        
        if start_time:
            duration = (datetime.utcnow() - start_time).total_seconds()
            self._execution_durations[workflow_id].append(duration)
            
            # Keep only last 100 durations
            if len(self._execution_durations[workflow_id]) > 100:
                self._execution_durations[workflow_id] = self._execution_durations[workflow_id][-100:]
        
        if workflow_id in self._workflow_metrics:
            metrics = self._workflow_metrics[workflow_id]
            metrics.active_executions = max(0, metrics.active_executions - 1)
            metrics.completed_today += 1
            
            # Update success rate (rolling average)
            old_successes = metrics.success_rate * (metrics.total_executions - 1)
            new_successes = old_successes + (1 if success else 0)
            metrics.success_rate = new_successes / metrics.total_executions
            
            # Update duration metrics
            durations = self._execution_durations.get(workflow_id, [])
            if durations:
                metrics.avg_duration_seconds = sum(durations) / len(durations)
                sorted_durations = sorted(durations)
                p95_idx = int(len(sorted_durations) * 0.95)
                metrics.p95_duration_seconds = sorted_durations[min(p95_idx, len(sorted_durations) - 1)]
    
    def track_resource_utilization(
        self,
        resource_id: str,
        utilization_percent: float,
        queue_size: int = 0
    ) -> None:
        """Track resource utilization."""
        self._resource_utilization[resource_id] = utilization_percent
        self._resource_queues[resource_id] = queue_size
    
    async def start(self) -> None:
        """Start the monitor."""
        self._running = True
        self._monitor_task = asyncio.create_task(self._monitor_loop())
    
    async def stop(self) -> None:
        """Stop the monitor."""
        self._running = False
        if self._monitor_task:
            self._monitor_task.cancel()
            try:
                await self._monitor_task
            except asyncio.CancelledError:
                pass
    
    async def _monitor_loop(self) -> None:
        """Main monitoring loop."""
        while self._running:
            try:
                await self._run_health_checks()
                await self._check_sla_compliance()
                await self._detect_bottlenecks()
                await self._update_trends()
                await asyncio.sleep(self._check_interval)
            except asyncio.CancelledError:
                break
            except Exception as e:
                print(f"Monitor error: {e}")
                await asyncio.sleep(self._check_interval)
    
    async def _run_health_checks(self) -> List[HealthCheck]:
        """Run all registered health checks."""
        results = []
        
        for check_func in self._health_checks:
            try:
                if asyncio.iscoroutinefunction(check_func):
                    result = await check_func()
                else:
                    result = check_func()
                results.append(result)
                
                # Generate alert if unhealthy
                if result.status in (HealthStatus.WARNING, HealthStatus.CRITICAL):
                    await self._create_alert(
                        severity=AlertSeverity.WARNING if result.status == HealthStatus.WARNING else AlertSeverity.CRITICAL,
                        title=f"Health Check Failed: {result.check_name}",
                        description=result.message,
                        details=result.details
                    )
            except Exception as e:
                results.append(HealthCheck(
                    check_name="health_check_error",
                    status=HealthStatus.UNKNOWN,
                    message=f"Health check error: {e}"
                ))
        
        return results
    
    async def _check_sla_compliance(self) -> None:
        """Check SLA compliance for active executions."""
        now = datetime.utcnow()
        
        for execution_id, start_time in self._execution_starts.items():
            elapsed_hours = (now - start_time).total_seconds() / 3600
            
            # Check against SLAs
            for sla_name, sla in self._sla_definitions.items():
                target = sla.target_completion_hours
                warning_hours = target * (sla.warning_threshold_percent / 100)
                escalation_hours = target * (sla.escalation_threshold_percent / 100)
                
                if elapsed_hours >= target:
                    await self._create_alert(
                        severity=AlertSeverity.CRITICAL,
                        title=f"SLA Breach: {sla_name}",
                        description=f"Execution {execution_id} exceeded SLA of {target} hours",
                        execution_id=execution_id,
                        recommended_actions=[
                            "Investigate root cause",
                            "Escalate to management",
                            "Update stakeholders"
                        ]
                    )
                elif elapsed_hours >= escalation_hours:
                    await self._create_alert(
                        severity=AlertSeverity.ERROR,
                        title=f"SLA At Risk: {sla_name}",
                        description=f"Execution {execution_id} at {(elapsed_hours/target)*100:.0f}% of SLA",
                        execution_id=execution_id,
                        recommended_actions=[
                            "Review blockers",
                            "Allocate additional resources",
                            "Prepare escalation"
                        ]
                    )
                elif elapsed_hours >= warning_hours:
                    await self._create_alert(
                        severity=AlertSeverity.WARNING,
                        title=f"SLA Warning: {sla_name}",
                        description=f"Execution {execution_id} approaching SLA threshold",
                        execution_id=execution_id,
                        recommended_actions=["Monitor closely"]
                    )
    
    async def _detect_bottlenecks(self) -> List[BottleneckPrediction]:
        """Detect and predict bottlenecks."""
        predictions = []
        
        # Check resource utilization
        for resource_id, utilization in self._resource_utilization.items():
            queue_size = self._resource_queues.get(resource_id, 0)
            
            if utilization >= 90:
                predictions.append(BottleneckPrediction(
                    resource=resource_id,
                    severity="high",
                    predicted_impact="Significant delays expected",
                    confidence=0.9,
                    timeframe="Immediate",
                    recommendations=[
                        f"Reduce load on {resource_id}",
                        "Scale up or distribute work",
                        "Consider alternative resources"
                    ]
                ))
                
                await self._create_alert(
                    severity=AlertSeverity.ERROR,
                    title=f"Resource Bottleneck: {resource_id}",
                    description=f"Resource at {utilization:.0f}% utilization with {queue_size} items queued"
                )
            elif utilization >= 75:
                predictions.append(BottleneckPrediction(
                    resource=resource_id,
                    severity="medium",
                    predicted_impact="Potential delays if load increases",
                    confidence=0.7,
                    timeframe="Next 1-2 hours",
                    recommendations=[
                        "Monitor closely",
                        "Prepare contingency"
                    ]
                ))
        
        # Check workflow backlogs
        for workflow_id, metrics in self._workflow_metrics.items():
            if metrics.active_executions > 10:  # Configurable threshold
                predictions.append(BottleneckPrediction(
                    resource=f"workflow_{workflow_id}",
                    severity="medium",
                    predicted_impact=f"{metrics.active_executions} workflows queued",
                    confidence=0.8,
                    timeframe="Current",
                    recommendations=[
                        "Check for stuck executions",
                        "Review agent performance"
                    ]
                ))
        
        return predictions
    
    async def _update_trends(self) -> None:
        """Update trend analysis for workflows."""
        for workflow_id, durations in self._execution_durations.items():
            if len(durations) < 10:
                continue
            
            metrics = self._workflow_metrics.get(workflow_id)
            if not metrics:
                continue
            
            # Compare recent vs older durations
            recent = durations[-10:]
            older = durations[-20:-10] if len(durations) >= 20 else durations[:10]
            
            recent_avg = sum(recent) / len(recent)
            older_avg = sum(older) / len(older)
            
            if recent_avg > older_avg * 1.2:
                metrics.duration_trend = "degrading"
            elif recent_avg < older_avg * 0.8:
                metrics.duration_trend = "improving"
            else:
                metrics.duration_trend = "stable"
    
    async def _create_alert(
        self,
        severity: AlertSeverity,
        title: str,
        description: str,
        workflow_id: Optional[str] = None,
        execution_id: Optional[str] = None,
        step_id: Optional[str] = None,
        recommended_actions: Optional[List[str]] = None,
        details: Optional[Dict[str, Any]] = None
    ) -> HealthAlert:
        """Create and track an alert."""
        import uuid
        
        alert = HealthAlert(
            id=str(uuid.uuid4()),
            severity=severity,
            title=title,
            description=description,
            workflow_id=workflow_id,
            execution_id=execution_id,
            step_id=step_id,
            recommended_actions=recommended_actions or [],
            expires_at=datetime.utcnow() + timedelta(hours=24)
        )
        
        # Store alert
        self._active_alerts[alert.id] = alert
        
        # Update metrics
        if workflow_id and workflow_id in self._workflow_metrics:
            self._workflow_metrics[workflow_id].active_alerts += 1
            
            # Update health status
            if severity == AlertSeverity.CRITICAL:
                self._workflow_metrics[workflow_id].current_health = HealthStatus.CRITICAL
            elif severity == AlertSeverity.ERROR:
                if self._workflow_metrics[workflow_id].current_health != HealthStatus.CRITICAL:
                    self._workflow_metrics[workflow_id].current_health = HealthStatus.WARNING
        
        # Notify callback
        if self._alert_callback:
            if asyncio.iscoroutinefunction(self._alert_callback):
                await self._alert_callback(alert)
            else:
                self._alert_callback(alert)
        
        return alert
    
    async def acknowledge_alert(self, alert_id: str) -> bool:
        """Acknowledge an alert."""
        if alert_id in self._active_alerts:
            self._active_alerts[alert_id].acknowledged = True
            return True
        return False
    
    async def resolve_alert(self, alert_id: str) -> bool:
        """Resolve an alert."""
        if alert_id in self._active_alerts:
            alert = self._active_alerts[alert_id]
            alert.resolved = True
            alert.resolved_at = datetime.utcnow()
            
            # Update metrics
            if alert.workflow_id and alert.workflow_id in self._workflow_metrics:
                self._workflow_metrics[alert.workflow_id].active_alerts -= 1
            
            return True
        return False
    
    def get_active_alerts(
        self,
        workflow_id: Optional[str] = None,
        min_severity: Optional[AlertSeverity] = None
    ) -> List[HealthAlert]:
        """Get active alerts with optional filtering."""
        alerts = [a for a in self._active_alerts.values() if not a.resolved]
        
        if workflow_id:
            alerts = [a for a in alerts if a.workflow_id == workflow_id]
        
        if min_severity:
            severity_order = {AlertSeverity.INFO: 0, AlertSeverity.WARNING: 1, 
                           AlertSeverity.ERROR: 2, AlertSeverity.CRITICAL: 3}
            min_level = severity_order.get(min_severity, 0)
            alerts = [a for a in alerts if severity_order.get(a.severity, 0) >= min_level]
        
        return sorted(alerts, key=lambda a: a.created_at, reverse=True)
    
    def get_workflow_metrics(
        self,
        workflow_id: Optional[str] = None
    ) -> Dict[str, WorkflowMetrics]:
        """Get workflow metrics."""
        if workflow_id:
            return {workflow_id: self._workflow_metrics.get(workflow_id)}
        return self._workflow_metrics.copy()
    
    def get_health_summary(self) -> Dict[str, Any]:
        """Get overall health summary."""
        critical = len([a for a in self._active_alerts.values() 
                       if not a.resolved and a.severity == AlertSeverity.CRITICAL])
        errors = len([a for a in self._active_alerts.values() 
                     if not a.resolved and a.severity == AlertSeverity.ERROR])
        warnings = len([a for a in self._active_alerts.values() 
                       if not a.resolved and a.severity == AlertSeverity.WARNING])
        
        if critical > 0:
            overall_status = HealthStatus.CRITICAL
        elif errors > 0:
            overall_status = HealthStatus.WARNING
        else:
            overall_status = HealthStatus.HEALTHY
        
        return {
            "overall_status": overall_status.name,
            "active_alerts": {
                "critical": critical,
                "error": errors,
                "warning": warnings,
                "total": len(self._active_alerts)
            },
            "workflow_count": len(self._workflow_metrics),
            "active_executions": sum(m.active_executions for m in self._workflow_metrics.values()),
            "resource_utilization": dict(self._resource_utilization)
        }
